version: '3.8'

services:
  web:
    build: .
    ports:
      - "8051:8051"
    environment:
      - PORT=8051
      - DEBUG=True
    command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8051", "main:application"]
